[package]
org = "ballerinax"
name = "wso2.controlplane"
version = "@toml.version@"
distribution = "@ballerina.version@"
repository = "https://github.com/ballerina-platform/module-ballerinax-wso2.controlplane"
license = ["Apache-2.0"]

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/wso2.controlplane-native-@project.version@.jar"
