[package]
org = "ballerinax"
name = "wso2.controlplane"
version = "1.1.0"
distribution = "2201.12.2"
repository = "https://github.com/ballerina-platform/module-ballerinax-wso2.controlplane"
license = ["Apache-2.0"]

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/wso2.controlplane-native-1.1.0-SNAPSHOT.jar"
